name: CI

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [17]
        scala: ['3.2']
        include:
          - scala: '3.2'
            scala-version: 3.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}

      - name: Check and compile
        run: sbt ++${{ matrix.scala-version }} scalafmtCheckAll compile

      - name: Test
        run: >
          sbt genCode test

# (still way to go for scala3 tooling)
#      - name: Test with coverage
#        run: >
#          sbt coverage genCode test
#      - name: Coveralls
#        if: startsWith(matrix.scala, '3')
#        run: sbt ++${{ matrix.scala-version }} coverageAggregate coveralls
#        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
