name: tscfg tests/coverage

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and Test
        run: |
          sbt coverage test
      - name: Coverage report
        run: |
          sbt coverageReport

      # hmm, seems like we better use a diff coverage service -- https://github.com/scoverage/sbt-coveralls/issues/126
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
